name: mlproject-ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-mlproject:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install MLflow
      run: |
        pip install mlflow pandas scikit-learn

    - name: Run MLflow Project
      run: |
        mlflow run MLProject -P data_path=MLProject/dataset_preprocessing/spotify_preprocessed_train.csv

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns/